# Generated by Django 3.2.11 on 2022-02-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('duration', models.TextField(default='15 Minutes')),
                ('student', models.TextField()),
                ('helper', models.TextField()),
                ('feedback', models.TextField(default='')),
            ],
        ),
    ]
