# Generated by Django 3.2.11 on 2022-02-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='course',
        ),
    ]
