# Generated by Django 3.2.11 on 2022-02-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.TextField(default='15 Minutes'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(default=None),
        ),
    ]
